# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prview < Formula
  desc "GitHub-style git diff viewer in your browser"
  homepage "https://github.com/flatcoke/prview"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flatcoke/prview/releases/download/v0.5.0/prview_0.5.0_darwin_amd64.tar.gz"
      sha256 "761ecb38a3959e5dbbf623c8fa263cf8afd19580e3e9eafc905b81bee8bcf5c2"

      define_method(:install) do
        bin.install "prview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flatcoke/prview/releases/download/v0.5.0/prview_0.5.0_darwin_arm64.tar.gz"
      sha256 "9b931ef8604f03857b6f1831ea0fc5e5bb63fa0f99afadc224509866b0a7326c"

      define_method(:install) do
        bin.install "prview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flatcoke/prview/releases/download/v0.5.0/prview_0.5.0_linux_amd64.tar.gz"
      sha256 "d9bd7579491e1ba68cdfaa7b0947fb9beff0419007457516f93e1b7c2af54af2"
      define_method(:install) do
        bin.install "prview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flatcoke/prview/releases/download/v0.5.0/prview_0.5.0_linux_arm64.tar.gz"
      sha256 "00887c9ebb5b3aea30884614e698095923a91e7a995e8d17c8caac381ebed0e9"
      define_method(:install) do
        bin.install "prview"
      end
    end
  end

  test do
    system "#{bin}/prview", "--help"
  end
end
