# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prview < Formula
  desc "GitHub-style git diff viewer in your browser"
  homepage "https://github.com/flatcoke/prview"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flatcoke/prview/releases/download/v0.2.1/prview_0.2.1_darwin_amd64.tar.gz"
      sha256 "c69bd350bd1d92e3169512b8c987153ae7e8efd7db276da672c0fd2014dee968"

      define_method(:install) do
        bin.install "prview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flatcoke/prview/releases/download/v0.2.1/prview_0.2.1_darwin_arm64.tar.gz"
      sha256 "e8b552649838ab95ea65ef9a51e5a9c89556c64886ea111e0a7df3020d892951"

      define_method(:install) do
        bin.install "prview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flatcoke/prview/releases/download/v0.2.1/prview_0.2.1_linux_amd64.tar.gz"
      sha256 "189a027e688ab11defb45449f9edd5bb21dd22856915f4e964330e1a14c5ee8f"
      define_method(:install) do
        bin.install "prview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flatcoke/prview/releases/download/v0.2.1/prview_0.2.1_linux_arm64.tar.gz"
      sha256 "6d0e8a105aa0cb2144b7cc7d756d381be33b1592339ea96405045e7eabaa020c"
      define_method(:install) do
        bin.install "prview"
      end
    end
  end

  test do
    system "#{bin}/prview", "--help"
  end
end
